//! Real hardware (ADR-0068): the hardware profile of the services, the USB
//! image a real machine boots from, and the smoke test that boots that
//! image as a real PC would (no virtio: NVMe, SATA, Intel Ethernet, xHCI).

use std::io::{BufRead, BufReader};
use std::process::Stdio;
use std::sync::mpsc;
use std::thread;
use std::time::{Duration, Instant};

use super::*;

/// The image a machine boots from: GPT, one EFI system partition.
pub const USB_IMAGE: &str = "build/oceans-usb.img";
/// The hardware smoke test's NVMe disk (the root filesystem).
const HW_NVME_IMAGE: &str = "build/smoke-hw-nvme.img";
const HW_NVME_SIZE: usize = 64 << 20;
/// Its SATA disk (ADR-0069), on q35's AHCI controller: mounted at /sata.
const HW_SATA_IMAGE: &str = "build/smoke-hw-sata.img";
const HW_SATA_SIZE: usize = 16 << 20;
/// Each hardware smoke boot, start to finish.
const HW_TIMEOUT: Duration = Duration::from_secs(300);

/// The services of a real machine, from `config/services.conf`: the same
/// system, but the root filesystem lives on the NVMe SSD (formatted only if
/// its start is blank, else left untouched and files kept in memory), not
/// on a virtio disk. A SATA disk stays where `services.conf` puts it, at
/// /sata (ADR-0069). Generated, never kept as a copy: each change below
/// must find exactly what it changes.
pub fn hardware_services(text: &str) -> Result<String> {
    let mut text = remove_service(text, "block")?;
    text = remove_service(&text, "nvmefs")?;
    for (from, to) in [
        ("    use = block\n", "    use = nvme as block\n"),
        ("    use = nvmefs as mount:nvme\n", ""),
    ] {
        if text.matches(from).count() != 1 {
            return Err(format!(
                "services.conf: cannot make the hardware profile (`{}` must appear once)",
                from.trim()
            ));
        }
        text = text.replacen(from, to, 1);
    }
    Ok(format!(
        "# The hardware profile (ADR-0068), generated by `cargo xtask` from\n\
         # config/services.conf: the root filesystem on the NVMe SSD.\n\n{text}"
    ))
}

/// `text` without the stanza `service NAME` (to the next blank line).
fn remove_service(text: &str, name: &str) -> Result<String> {
    let header = format!("service {name}\n");
    let start = text
        .match_indices(&header)
        .find(|(at, _)| *at == 0 || text.as_bytes()[at - 1] == b'\n')
        .map(|(at, _)| at)
        .ok_or(format!("services.conf has no `service {name}`"))?;
    let end = text[start..]
        .find("\n\n")
        .map_or(text.len(), |len| start + len + 2);
    Ok(format!("{}{}", &text[..start], &text[end..]))
}

/// `cargo xtask usb`: the image to write to a USB stick for a real machine
/// (the hardware profile).
pub fn usb(profile: Profile) -> Result {
    let esp = build_image_for(
        profile,
        None,
        Setup::Hardware,
        &release::ImageKeys::development()?,
    )?;
    write_usb_image(&esp)?;
    println!(
        "{USB_IMAGE} is a development image: it trusts the development key, whose seed is \
         public (`cargo xtask release` builds one that trusts only a release key, ADR-0072)"
    );
    println!(
        "{USB_IMAGE} is ready: write it to a USB stick (Rufus, dd, balenaEtcher) and boot a \
         UEFI machine from it (docs/hardware/compatibility.md)"
    );
    Ok(())
}

/// `cargo xtask usb-secure-boot`: the same image, signed for Secure Boot
/// with the development Secure Boot key (ADR-0091).
pub fn usb_secure_boot(profile: Profile) -> Result {
    let esp = build_image_for(
        profile,
        None,
        Setup::Hardware,
        &release::ImageKeys::development()?,
    )?;
    let key = crate::secure_boot::development_key()?;
    crate::secure_boot::write_secure_usb_image(&esp, &key)?;
    println!(
        "{USB_IMAGE} is signed for Secure Boot with the development Secure Boot key: enrol \
         tools/keys/oceans-dev-secure-boot.cer (on the stick, {}) in the firmware's db to boot \
         it with Secure Boot on",
        crate::secure_boot::CERTIFICATE_FILE
    );
    Ok(())
}

/// Packs `esp` into [`USB_IMAGE`]: GPT, one EFI system partition with
/// FAT32 holding its files (made here, ADR-0092).
pub fn write_usb_image(esp: &Path) -> Result {
    let used = disk_image::tree_size(esp)?;
    // Room for the second slot and an update file beside it (ADR-0071).
    let esp_mib = (used / (1 << 20) * 3 + 48).max(64);
    let kernel = fs::read(esp.join("boot").join("a").join(KERNEL_PACKAGE)).unwrap_or_default();
    let mut sources = vec![esp.join("EFI"), esp.join("boot"), esp.join("limine.conf")];
    // A Secure Boot image's certificate, at the root (ADR-0091).
    let certificate = esp.join(crate::secure_boot::CERTIFICATE_FILE);
    if certificate.is_file() {
        sources.push(certificate);
    }
    disk_image::gpt_image(
        &root().join(USB_IMAGE),
        &[disk_image::Volume {
            kind: oceans_gpt::EFI_SYSTEM,
            name: "EFI system partition",
            label: "OCEANS",
            mib: esp_mib,
            sources,
        }],
        &kernel,
    )?;
    println!(
        "{USB_IMAGE}: GPT, an EFI system partition of {esp_mib} MiB ({} MiB of files)",
        used >> 20
    );
    Ok(())
}

/// The hardware image's boot partition (ADR-0071): the release in slot
/// `boot/a`, and Limine's configuration in both places it looks
/// (`/limine.conf` first, then `/boot/limine/limine.conf`).
pub fn slot_layout(esp: &Path, release: &str) -> Result {
    let boot = esp.join("boot");
    let slot = boot.join("a");
    fs::create_dir_all(&slot).map_err(|e| format!("cannot create {}: {e}", slot.display()))?;
    for name in [KERNEL_PACKAGE, "initrd"] {
        fs::rename(boot.join(name), slot.join(name))
            .map_err(|e| format!("cannot move {name} into slot a: {e}"))?;
    }
    fs::write(slot.join("release"), format!("{release}\n"))
        .map_err(|e| format!("cannot write the release: {e}"))?;
    let conf = boot_configuration(&[(&format!("Oceans {release}"), 'a')]);
    for path in [
        esp.join("limine.conf"),
        boot.join("limine").join("limine.conf"),
    ] {
        fs::write(&path, &conf).map_err(|e| format!("cannot write {}: {e}", path.display()))?;
    }
    Ok(())
}

/// Limine's configuration for the slots, first entry first: the same text
/// `update` writes (user/utils/src/bin/update.rs).
fn boot_configuration(entries: &[(&str, char)]) -> String {
    let mut conf = String::from(
        "# Oceans boot configuration (ADR-0071), written by `update`.\ntimeout: 3\n\n",
    );
    for (i, (name, slot)) in entries.iter().enumerate() {
        if i > 0 {
            conf.push('\n');
        }
        conf.push_str(&format!(
            "/{name}\n    protocol: limine\n    path: boot():/boot/{slot}/{KERNEL_PACKAGE}\n    \
             module_path: boot():/boot/{slot}/initrd\n"
        ));
    }
    conf
}

/// A system update (ADR-0071): this image's kernel and boot archive as
/// release `version`, signed with `key`.
pub fn system_package(
    esp: &Path,
    version: &str,
    key: &oceans_dev::DeveloperKey,
    description: &str,
    secure_boot: Option<&oceans_dev::secure_boot::SecureBootKey>,
) -> Result<Vec<u8>> {
    let slot = esp.join("boot").join("a");
    let kernel = fs::read(slot.join(KERNEL_PACKAGE)).map_err(|e| format!("kernel: {e}"))?;
    let initrd = fs::read(slot.join("initrd")).map_err(|e| format!("initrd: {e}"))?;
    let archive = oceans_archive::Archive::parse(&initrd)
        .map_err(|e| format!("the boot archive does not parse: {e:?}"))?;
    let release = format!("{version} {RELEASE_CHANNEL}\n");
    let entries: Vec<(&str, &[u8])> = archive
        .files()
        .map(|file| {
            if file.name == "release" {
                (file.name, release.as_bytes())
            } else {
                (file.name, file.data)
            }
        })
        .collect();
    let mut new_initrd = vec![0u8; oceans_archive::archive_len(&entries)];
    oceans_archive::write(&entries, &mut new_initrd)
        .map_err(|e| format!("cannot build the boot archive: {e:?}"))?;
    let manifest = format!(
        "id = system.oceans\nname = Oceans\nversion = {version}\npublisher = {}\n\
         description = {description}\narchitecture = x86_64\n\
         api = 1\nchannel = {RELEASE_CHANNEL}\nentry = {KERNEL_PACKAGE}\n",
        key.publisher
    );
    // For systems that boot with Secure Boot (ADR-0092): the slot's signed
    // Limine and its configuration, naming this kernel and boot archive.
    let boot_files = match secure_boot {
        Some(sb_key) => Some(crate::secure_boot::slot_boot_files(
            release.trim(),
            &kernel,
            &new_initrd,
            sb_key,
        )?),
        None => None,
    };
    let mut files: Vec<(&str, &[u8])> = vec![
        ("manifest", manifest.as_bytes()),
        (KERNEL_PACKAGE, &kernel),
        ("initrd", &new_initrd),
    ];
    if let Some((efi, config)) = &boot_files {
        files.push((crate::secure_boot::UPDATE_EFI, efi));
        files.push((crate::secure_boot::UPDATE_CONFIG, config.as_bytes()));
    }
    oceans_package::build(&files, &key.seed).map_err(|e| format!("cannot sign the update: {e:?}"))
}

/// The hardware smoke test's system packages:
/// - an update signed with its release key;
/// - one signed with the development key, which a release image does not
///   trust (refused before its files are looked at: placeholders keep it
///   small);
/// - a small one signed with the release key (the kernel, a placeholder
///   boot archive), for `app install` to refuse (ADR-0073): the update
///   itself is larger than the shell's limit for packages.
fn smoke_updates(esp: &Path) -> Result<(Vec<u8>, Vec<u8>, Vec<u8>)> {
    let update = system_package(
        esp,
        "0.1.1",
        &release::test_release_key(),
        "A system update (the hardware smoke test's)",
        None,
    )?;
    let manifest = format!(
        "id = system.oceans\nname = Oceans\nversion = 0.1.1\npublisher = {DEV_PUBLISHER}\n\
         architecture = x86_64\napi = 1\nentry = {KERNEL_PACKAGE}\n"
    );
    let placeholder: [(&str, &[u8]); 3] = [
        ("manifest", manifest.as_bytes()),
        (KERNEL_PACKAGE, b"placeholder"),
        ("initrd", b"placeholder"),
    ];
    let untrusted = oceans_package::build(&placeholder, &dev_seed()?)
        .map_err(|e| format!("cannot sign: {e:?}"))?;
    let key = release::test_release_key();
    let manifest = format!(
        "id = system.oceans\nname = Oceans\nversion = 0.1.2\npublisher = {}\n\
         architecture = x86_64\napi = 1\nentry = {KERNEL_PACKAGE}\n",
        key.publisher
    );
    let kernel = fs::read(esp.join("boot").join("a").join(KERNEL_PACKAGE))
        .map_err(|e| format!("kernel: {e}"))?;
    let small: [(&str, &[u8]); 3] = [
        ("manifest", manifest.as_bytes()),
        (KERNEL_PACKAGE, &kernel),
        ("initrd", b"placeholder"),
    ];
    let system =
        oceans_package::build(&small, &key.seed).map_err(|e| format!("cannot sign: {e:?}"))?;
    Ok((update, untrusted, system))
}

/// Copies `files` (name, bytes) to the root of [`USB_IMAGE`]'s partition.
fn copy_to_usb(files: &[(&str, &[u8])]) -> Result {
    let mut fat = disk_image::open_partition(&root().join(USB_IMAGE), 1)?;
    for (name, bytes) in files {
        disk_image::put_file(&mut fat, oceans_fat::ROOT, name, bytes)?;
    }
    fat.sync().map_err(|e| format!("{USB_IMAGE}: {e:?}"))
}

/// The hardware smoke test's first boot: a blank NVMe SSD becomes the root.
const HW_SCRIPT: &[&[u8]] = &[
    b"uname\r\n",
    b"write /hw-note.txt kept on the nvme root\r\n",
    b"write /sata/hw-sata.txt kept on the sata disk\r\n",
    b"ls /sata\r\n",
    b"app list\r\n",
    b"ls /usb\r\n",
    b"run ifconfig out use:net\r\n",
    b"run sysreport out devices sysinfo use:net use:usb\r\n",
    // System updates (ADR-0071): one signed with the development key is
    // refused, since a release image trusts only its release key
    // (ADR-0072); the release-signed one goes into slot b.
    b"run update out use:fs -- status\r\n",
    b"run update out use:fs -- apply /usb/untrusted.opk\r\n",
    b"run update out use:fs -- apply /usb/update.opk\r\n",
    // Restarting into the update (ADR-0085): the real ACPI reset.
    b"reboot\r\n",
];
const HW_EXPECT: &[Expect] = &[
    Expect::Contains("smp: 4 CPUs online"),
    Expect::Contains("ACPI: switching off through PM1 control at io 0x604"),
    // The microphone codec's input (ADR-0087).
    Expect::Contains("hda: input: microphone (pin 0x"),
    Expect::Line("Stopping the system, then restarting..."),
    Expect::Contains("init: asked to restart: stopping the system"),
    Expect::Contains("init: disks synced"),
    Expect::Contains("services stopped"),
    Expect::Contains("power: restarting"),
    // The disks were told (ADR-0086).
    Expect::Contains("nvme: the controller is shut down"),
    Expect::Contains("ahci: the disk is in standby"),
    Expect::Contains("init: core stopped"),
    Expect::Contains("(ABI 16)"),
    Expect::Contains("fs: formatted a blank disk"),
    // The SATA disk (ADR-0069): identified, formatted, written.
    Expect::Contains("ahci: port 0: QEMU HARDDISK (serial oceans-sata, firmware "),
    Expect::Contains("ahci: port 0: 32768 sectors (16 MiB), 512-byte sectors"),
    Expect::Contains("fs (satafs): formatted a blank disk: "),
    Expect::Contains("fs: /sata: a mounted filesystem"),
    Expect::Line("  hw-sata.txt"),
    // Only the app the image brings (ADR-0080), signed with its key.
    Expect::Contains("app.oceans.calculator  1.0.0  Calculator"),
    Expect::Contains("app.oceans.settings  1.0.0  Settings"),
    Expect::Contains("app.oceans.files  1.0.0  Files"),
    Expect::Contains("app.oceans.activity  1.0.0  Activity Monitor"),
    Expect::Contains("app.oceans.editor  1.0.0  Text Editor"),
    Expect::Contains("app.oceans.viewer  1.0.0  Image Viewer"),
    // The boot stick itself, as removable media (ADR-0035): its ESP.
    Expect::Line("  EFI/"),
    Expect::Contains("cpu baseline (x86-64-v2, NX, APIC): SSE3 SSSE3"),
    Expect::Contains("NVMe SSD (any vendor): driver nvme (ADR-0040), attached"),
    Expect::Contains("SATA AHCI controller (any vendor): driver ahci (ADR-0069), attached"),
    Expect::Contains("USB 3 xHCI controller (any vendor): driver xhci (ADR-0032)"),
    Expect::Contains(
        "Intel High Definition Audio controller (any vendor): driver hda (ADR-0079, ADR-0087): output and input",
    ),
    Expect::Contains("Intel 82574L Ethernet: driver e1000e (ADR-0041), attached"),
    Expect::Contains("Display controller: UEFI GOP framebuffer"),
    Expect::Contains("QEMU USB Keyboard"),
    Expect::Contains("network: 10.0.2.15/24"),
    Expect::Line("tier 1 baseline: met"),
    Expect::Line("update: running Oceans 0.1.0 alpha (slot a)"),
    Expect::Line("update: starts first: slot a (0.1.0 alpha)"),
    Expect::Line("update: slot b is empty"),
    Expect::Line("update: refused: signed with a key this system does not trust"),
    Expect::Line("update: Oceans 0.1.1 alpha from Oceans Test Release, verified; writing slot b"),
    Expect::Contains("update: Oceans 0.1.1 alpha installed in slot b"),
];
/// The second boot: the root filesystem and the SATA disk's files are
/// still there.
/// The second boot: the update started (slot b), with the previous
/// release in the boot menu.
const HW_REBOOT_SCRIPT: &[&[u8]] = &[
    b"cat /hw-note.txt\r\n",
    b"cat /sata/hw-sata.txt\r\n",
    b"cat /bin/release\r\n",
    b"run update out use:fs -- status\r\n",
    b"run update out use:fs -- apply /usb/update.opk\r\n",
    // Core never installs a system package as an app.
    b"app install /usb/system.opk\r\n",
    // Switching off (ADR-0085): ACPI S5, which ends QEMU.
    b"shutdown\r\n",
];
const HW_REBOOT_EXPECT: &[Expect] = &[
    Expect::Line("Stopping the system, then switching off..."),
    Expect::Contains("init: asked to switch off: stopping the system"),
    Expect::Contains("init: disks synced"),
    Expect::Contains("power: switching off (ACPI S5)"),
    Expect::Contains("nvme: the controller is shut down"),
    Expect::Contains("ahci: the disk is in standby"),
    Expect::Contains("fs: mounted the disk: generation"),
    Expect::Line("kept on the nvme root"),
    Expect::Contains("fs (satafs): mounted the disk: generation"),
    Expect::Line("kept on the sata disk"),
    Expect::Line("0.1.1 alpha"),
    Expect::Line("update: running Oceans 0.1.1 alpha (slot b)"),
    Expect::Line("update: starts first: slot b (0.1.1 alpha)"),
    Expect::Line("update: previous: slot a (0.1.0 alpha)"),
    Expect::Line("update: refused: 0.1.1 is not newer than the running 0.1.1"),
    Expect::Contains("app: /usb/system.opk: a system update, not an app: apply it with `update`"),
];

/// `cargo xtask smoke-hw`: the USB image booted as a real PC would.
pub fn smoke_hw(profile: Profile) -> Result {
    // A release image's keys (ADR-0072), with the test's release key.
    let keys = release::ImageKeys::release(&release::test_release_key());
    let esp = build_image_for(profile, None, Setup::Hardware, &keys)?;
    write_usb_image(&esp)?;
    let (update, untrusted, system) = smoke_updates(&esp)?;
    copy_to_usb(&[
        ("update.opk", &update),
        ("untrusted.opk", &untrusted),
        ("system.opk", &system),
    ])?;
    prepare_blank(HW_NVME_IMAGE, HW_NVME_SIZE, true)?;
    prepare_blank(HW_SATA_IMAGE, HW_SATA_SIZE, true)?;
    println!("hardware boot 1 of 2: from the USB image, a blank NVMe SSD and SATA disk");
    hw_boot(HW_SCRIPT, HW_EXPECT)?;
    println!("hardware boot 2 of 2: the same disks");
    hw_boot(HW_REBOOT_SCRIPT, HW_REBOOT_EXPECT)?;
    println!(
        "hardware smoke test passed: booted from the USB image; root on NVMe; SATA; e1000e; xHCI; \
         updated to slot b"
    );
    Ok(())
}

/// One boot of the USB image: the shell (on the serial line) gets each
/// script line at a prompt; the boot passes when every expectation is met.
/// A script ending with `reboot` or `shutdown` (ADR-0085) must make QEMU
/// exit by itself (`-no-reboot`), cleanly, with no power fallback used.
fn hw_boot(script: &[&[u8]], expected: &[Expect]) -> Result {
    let qemu = find_qemu()?;
    let firmware = find_firmware(&qemu)?;
    let mut pflash = std::ffi::OsString::from("if=pflash,format=raw,readonly=on,file=");
    pflash.push(&firmware);
    let monitor_port = free_tcp_port()?;
    let serial_port = free_tcp_port()?;
    let mut child = Command::new(&qemu)
        .current_dir(root())
        // A Tier 1 machine (ADR-0005): x86-64-v2 or newer.
        .args(["-machine", "q35", "-cpu", "max", "-m", "512M", "-no-reboot"])
        // A four-core PC (ADR-0088).
        .args(["-smp", "4"])
        .args(serial_args(Some(serial_port)))
        .args(["-display", "none"])
        .arg("-drive")
        .arg(pflash)
        // No virtio anywhere: what a PC has.
        .arg("-drive")
        .arg(format!("if=none,id=nvme0,format=raw,file={HW_NVME_IMAGE}"))
        .args(["-device", "nvme,serial=oceans-hw,drive=nvme0"])
        // A SATA disk on q35's AHCI controller (its buses are ide.0 to
        // ide.5, one per port): port 0.
        .arg("-drive")
        .arg(format!("if=none,id=sata0,format=raw,file={HW_SATA_IMAGE}"))
        .args(["-device", "ide-hd,drive=sata0,bus=ide.0,serial=oceans-sata"])
        .args(["-netdev", "user,id=net0", "-device", "e1000e,netdev=net0"])
        // The monitor: where each CPU is, if the boot hangs.
        .arg("-monitor")
        .arg(format!("tcp:127.0.0.1:{monitor_port},server=on,wait=off"))
        .args([
            "-device",
            "qemu-xhci,id=usb",
            "-device",
            "usb-kbd,bus=usb.0,port=1",
        ])
        .arg("-drive")
        .arg(format!("if=none,id=stick,format=raw,file={USB_IMAGE}"))
        .args([
            "-device",
            "usb-storage,bus=usb.0,port=2,drive=stick,bootindex=0",
        ])
        // HD Audio, as on every PC (ADR-0079), recorded.
        .arg("-audiodev")
        .arg(audiodev(true, "build/smoke-hw-audio.wav"))
        .args([
            "-device",
            "intel-hda",
            "-device",
            "hda-output,audiodev=snd0",
        ])
        // And a microphone, as on most PCs (ADR-0087).
        .arg("-audiodev")
        .arg(input_audiodev(true))
        .args(["-device", "hda-micro,audiodev=snd1,cad=1"])
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .spawn()
        .map_err(|e| format!("failed to start QEMU: {e}"))?;
    let stdout = connect_serial(&mut child, serial_port)?;
    let mut input = stdout
        .try_clone()
        .map_err(|e| format!("the serial line: {e}"))?;
    let (lines_tx, lines) = mpsc::channel::<std::result::Result<String, ()>>();
    thread::spawn(move || {
        let mut reader = BufReader::new(stdout);
        let mut line = Vec::new();
        while let Ok(buffer) = reader.fill_buf() {
            if buffer.is_empty() {
                break;
            }
            let (consumed, prompt) = {
                let mut consumed = 0;
                let mut prompt = false;
                for &byte in buffer {
                    consumed += 1;
                    if byte == b'\n' {
                        let _ = lines_tx.send(Ok(String::from_utf8_lossy(&line).into_owned()));
                        line.clear();
                    } else {
                        line.push(byte);
                        if line.ends_with(SHELL_PROMPT) {
                            prompt = true;
                            break;
                        }
                    }
                }
                (consumed, prompt)
            };
            reader.consume(consumed);
            if prompt {
                let _ = lines_tx.send(Err(()));
            }
        }
    });

    let deadline = Instant::now() + HW_TIMEOUT;
    let mut unmet: Vec<Expect> = expected.to_vec();
    let mut commands = script.iter();
    let ends_with_power = script
        .last()
        .is_some_and(|last| matches!(*last, b"reboot\r\n" | b"shutdown\r\n"));
    let mut power_sent = false;
    let mut done_at: Option<Instant> = None;
    let outcome = loop {
        if let Some(at) = done_at
            && Instant::now() >= at
        {
            break Ok(());
        }
        let wait = deadline.saturating_duration_since(Instant::now());
        let wait = done_at.map_or(wait, |at| {
            wait.min(at.saturating_duration_since(Instant::now()))
        });
        match lines.recv_timeout(wait) {
            Ok(Ok(line)) => {
                println!("  | {line}");
                if line.contains("KERNEL PANIC") {
                    break Err(format!("the kernel panicked: {line}"));
                }
                // The ACPI way failed and a fallback ran (ADR-0085).
                if line.contains("power: the ") || line.contains("power: forcing") {
                    break Err(format!("switching off or restarting failed: {line}"));
                }
                unmet.retain(|expect| !expect.matches(&line));
            }
            // A prompt: the next command, or (all sent) a moment for the
            // last output, then done.
            Ok(Err(())) => match commands.next() {
                Some(command) => {
                    for &byte in *command {
                        let _ = input.write_all(&[byte]).and_then(|()| input.flush());
                        thread::sleep(Duration::from_millis(5));
                    }
                    power_sent = ends_with_power && commands.len() == 0;
                }
                None => {
                    done_at.get_or_insert(Instant::now() + Duration::from_secs(2));
                }
            },
            Err(mpsc::RecvTimeoutError::Timeout) if done_at.is_some() => break Ok(()),
            Err(mpsc::RecvTimeoutError::Timeout) => {
                // What every thread waits on (the kernel's diagnostic key,
                // Ctrl+\), for a hang to be found afterwards.
                let _ = input.write_all(&[0x1c]).and_then(|()| input.flush());
                let until = Instant::now() + Duration::from_secs(3);
                while let Ok(Ok(line)) =
                    lines.recv_timeout(until.saturating_duration_since(Instant::now()))
                {
                    println!("  | {line}");
                }
                report_cpus(monitor_port);
                break Err(format!(
                    "hardware smoke boot timed out after {}s",
                    HW_TIMEOUT.as_secs()
                ));
            }
            // Switched off or restarted: QEMU ends by itself.
            Err(mpsc::RecvTimeoutError::Disconnected) if power_sent => break Ok(()),
            Err(mpsc::RecvTimeoutError::Disconnected) => break Err("QEMU exited".into()),
        }
    };
    if power_sent && outcome.is_ok() {
        let status = child.wait().map_err(|e| format!("waiting for QEMU: {e}"))?;
        if !status.success() {
            return Err(format!("QEMU ended with {status} after the power request"));
        }
    } else {
        // The hardware profile has no test exit: the boot ends here.
        let _ = child.kill();
        let _ = child.wait();
    }
    outcome?;
    if !unmet.is_empty() {
        return Err(format!("hardware boot output missing: {unmet:?}"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn boot_configurations_list_slots_in_order() {
        let conf = boot_configuration(&[
            ("Oceans 0.1.1 alpha", 'b'),
            ("Oceans 0.1.0 alpha (previous)", 'a'),
        ]);
        let first = conf.find("path: boot():/boot/b/oceans-kernel").unwrap();
        let second = conf.find("path: boot():/boot/a/oceans-kernel").unwrap();
        assert!(first < second);
        assert!(conf.contains("timeout: 3\n"));
        assert!(conf.contains("module_path: boot():/boot/b/initrd\n"));
    }

    #[test]
    fn the_hardware_profile_roots_on_nvme() {
        let text = include_str!("../../../config/services.conf");
        let hw = hardware_services(text).unwrap();
        assert!(!hw.contains("service block\n"));
        assert!(!hw.contains("service nvmefs\n"));
        assert!(!hw.contains("mount:nvme"));
        let fs = &hw[hw.find("service fs\n").unwrap()..];
        let fs = &fs[..fs.find("\n\n").unwrap()];
        assert!(fs.contains("    use = nvme as block\n"), "{fs}");
        // The SATA disk stays at /sata (ADR-0069).
        assert!(fs.contains("    use = satafs as mount:sata\n"), "{fs}");
        assert!(hw.contains("service sata\n") && hw.contains("service satafs\n"));
        // Everything else is as it was.
        assert!(hw.contains("service display\n") && hw.contains("service core\n"));
        assert!(hardware_services("service fs\n    use = other\n\n").is_err());
    }
}
